export const CATEGORIES = {
  CLEANING: 'CLEANING',
  ELECTRICIAN: 'ELECTRICIAN',
  PLUMBER: 'PLUMBER',
  PAINTER: 'PAINTER',
  BRICKLAYER: 'BRICKLAYER',
  BABYSITTER: 'BABYSITTER',
  OTHERS: 'OTHERS',
} as const; 